### ISSUE TITLE
free coin website 

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Gsnipe1blookethacks/blookethack#1]
it dosent work the website isnt a thing

**Comment by Gsnipe1blookethacks** [comment]
Hello Snowflake-Coder-H2o, You can paste the code from the free coins tab (in the middle of the different codes) straight into console. 
Thanks, Gsnipe1Blookethacks

**Comment by Gsnipe1blookethacks** [comment]
The free coins website also works now sorry about that blooket made me take the other one down 

Thanks, Gsnipe1Blookethacks

**Comment by Snowflake-Coder-H2o** [comment]
No problem! Thanks for accually replying!


-Snow

**Comment by Gsnipe1blookethacks** [comment]
yeah for sure thanks for using the code

**Comment by Snowflake-Coder-H2o** [comment]
No problem!

-Snow

**Comment by Gsnipe1blookethacks** [comment]
you make repositories for games?
