### ISSUE TITLE
hacks not working and a request

### ISSUE THREAD

**Issue by Blooper-glooper** [Gsnipe1blookethacks/blookethack#13]
The get all answers hack does not work in battle royale, it says it activates but just doesn't work and my request is that you make hacks for deceptive dinos when it comes out like a esp like gold quest and make get all answers work for that as well 
thanks in advance.

**Comment by Gsnipe1blookethacks** [comment]
I'm sorry but battle Royale hacks are currently down. I will try and get them, deceptive Dino, and spam open for dino box working.

Thanks,Gsnipe1

**Comment by Park-Sauce** [comment]
Deceptive dino hacks will most likely be available in 2-3 months.

**Comment by Blooper-glooper** [comment]
ok thank you

**Comment by Gsnipe1blookethacks** [comment]
Sorry I meant to say 2 weeks. I will have the hack up in about two weeks.

Thanks,Gsnipe1
