### ISSUE TITLE
Cool skid

### ISSUE THREAD

**Issue by smintf** [Gsnipe1blookethacks/blookethack#16]
Nice skid but [Blooketware/BlooketUI](https://github.com/Blooketware/BlooketUI/) is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License](https://github.com/Blooketware/BlooketUI/blob/main/LICENSE.md)

**Comment by Gsnipe1blookethacks** [comment]
It's my code though?

**Comment by smintf** [comment]
So i request you to take this filthy repository down before i send a copyright takedown request.

**Comment by smintf** [comment]
> It's my code though?

How?

**Comment by Gsnipe1blookethacks** [comment]
I didn't copy your code and paste it I made my own based on yours

**Comment by smintf** [comment]
NoDerivatives License.

> I didn't copy your code and paste it I made my own based on yours

**Comment by smintf** [comment]
Check [this](https://creativecommons.org/misuse-of-works/) if you want more clarity.

**Comment by Gsnipe1blookethacks** [comment]
Busy I'm sorry that ur upset but I have like 50 views a day and didn't copy your code is it really that big of a deal

**Comment by smintf** [comment]
> Busy I'm sorry that ur upset but I have like 50 views a day and didn't copy your code is it really that big of a deal

Fine man lets see if your this cocky after i send DMCA Takedown requests for violating the license under which my resides.

**Comment by Gsnipe1blookethacks** [comment]
You want a shoutout in the read me?

**Comment by Gsnipe1blookethacks** [comment]
What do you want me to do

**Comment by smintf** [comment]
> You want a shoutout in the read me?

No you either take this down of your own free will or i'll just send an email and get this repo taken down.

**Comment by smintf** [comment]
https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by Gsnipe1blookethacks** [comment]
Is there any other solution?

**Comment by smintf** [comment]
Idc if you fork the original repo.
But as my license specifically prohibits derivatives of my work (If you remix, transform, or build upon the material, you may not distribute the modified material.)

**Comment by smintf** [comment]
> Is there any other solution?

unless i relicense my work, definitely no.

**Comment by Gsnipe1blookethacks** [comment]
Can I just say that all the code came from you?

**Comment by smintf** [comment]
> Can I just say that all the code came from you?

Then you can just ***fork*** my repository.

**Comment by Gsnipe1blookethacks** [comment]
But I already spent 6 months getting 10 stars

**Comment by smintf** [comment]
That's not my problem. My problem is that your violating my license and in a sense endorsing other people to do the same .
¯\\_(ツ)_/¯

**Comment by Gsnipe1blookethacks** [comment]
Does it hurt you if I just keep it up and tell people to check out your stuff

**Comment by smintf** [comment]
So you can remove all the code that is a derivative of my work (all the files except `LICENSE`, `README.md` and `Spam Bots`) or take down this repo.

**Comment by smintf** [comment]
> Does it hurt you if I just keep it up and tell people to check out your stuff

Are you really trying to question my morality? when your the one violating licenses.

**Comment by smintf** [comment]
> But I already spent 6 months getting 10 stars

This repository is 3 months old btw.

**Comment by Gsnipe1blookethacks** [comment]
I'm not trying to question you I am just asking to pls let me keep it up if I give you full credit

**Comment by smintf** [comment]
> I'm not trying to question you I am just asking to pls let me keep it up if I give you full credit

My man there isn't a middle ground in licensing terms. there's only black and white i.e whether you violate the license or follow it.

**Comment by Gsnipe1blookethacks** [comment]
No it's not I got a cease and desist on my old one and told everyone to come to this one

**Comment by Gsnipe1blookethacks** [comment]
Can I pay you to let me keep it up

**Comment by smintf** [comment]
> Can I pay you to let me keep it up



> No it's not I got a cease and desist on my old one and told everyone to come to this one

???? what does it even prove if your not going to bother reading the license?

**Comment by Gsnipe1blookethacks** [comment]
Ok I'll take it down

**Comment by Gsnipe1blookethacks** [comment]
It's 1233 here so I will do it first thing tomorrow

**Comment by smintf** [comment]
??? are you stalling for time or something?

**Comment by Gsnipe1blookethacks** [comment]
I am literally complying can you just give me until the morning?

**Comment by smintf** [comment]
Merge [Pull Request 4](https://github.com/Gsnipe1blookethacks/blookethack/pull/17)
