### ISSUE TITLE
Good luck

### ISSUE THREAD

**Issue by Blooper-glooper** [Gsnipe1blookethacks/blookethack#20]
good luck on your finals and hope you get through those road blocks, don't worry bout the hacks.

**Comment by Gsnipe1blookethacks** [comment]
Thanks so much. I am going to try and keep them up but obviously, I need to keep my priorities.

Thanks,Gsnipe1

**Comment by 3kh0** [comment]
@Blooper-glooper These hacks, are not made by @Gsnipe1blookethacks , they were stolen from here: https://github.com/Blooketware/BlooketUI

**Comment by Gsnipe1blookethacks** [comment]
This is not even a hack menu what are you even talking about

**Comment by Gsnipe1blookethacks** [comment]
I'm sorry but these two repo codes are totally different I every way because they do different things

**Comment by Gsnipe1blookethacks** [comment]
This guy is making up random bs to try and get my code taken down

**Comment by Gsnipe1blookethacks** [comment]
If he could read he could see the Creative Commons license on this repo so he needs to stop waisting his time being an idiot

**Comment by Gsnipe1blookethacks** [comment]
@Blooper-glooper knows what is actually going on so @3kh0 you need to chill out and stop bugging other people
