### ISSUE TITLE
ALL HACKS

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Gsnipe1blookethacks/blookethack#4]
ALL HACKS WILL GET YOU BANNED FOR A MONTH OR PERMINITLY I THINK.

**Comment by Gsnipe1blookethacks** [comment]
I am so sorry snowflake,
Has your account been banned?

**Comment by Gsnipe1blookethacks** [comment]
If not then I can assure you that the new 500 coins code works

**Comment by Gsnipe1blookethacks** [comment]
If you would like to avoid being banned then checking the read me regularly could be a solution.

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks Yes a lot of my accounts got banned lmao. It's all good though. It's only banned for a month. 


-Snow

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks Also make your readme.md file make sure it says README.md so when you scroll all the way down, it will say what you want it to say. you have it named 1readme.md

-Snow

**Comment by Gsnipe1blookethacks** [comment]
Since this issue has been resolved I will now delete it.

Thank you,Gsnipe1
