### ISSUE TITLE
Hey 

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Gsnipe1blookethacks/blookethack#5]
Hey, i have a few codes that you might wanna check out. some of them might work But I dont know. I have a 500 coins, all answers correct if you want it.

Have a great day!

-Snow

**Comment by Park-Sauce** [comment]
GS will take care of this

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks I currently have the All Answers Correct and the daily tokens. If you still need them.

**Comment by Snowflake-Coder-H2o** [comment]
Never mind you already have the codes fixed.

Have a great day!

-Snow

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks Do you want a tower defense cheat it can remove all the annoying ducks that popup in games.

**Comment by Gsnipe1blookethacks** [comment]
Yeah sure thanks snow

**Comment by Gsnipe1blookethacks** [comment]
I just updated them, thanks Snow

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks No problem!

Have a great day!

-Snow

**Comment by Gsnipe1blookethacks** [comment]
You to snow

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks Thanks

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks Hey question do you want the script that is called Remove Annoying Ducks I can give it to you.

**Comment by Gsnipe1blookethacks** [comment]
Ok thanks

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks Do you want it?
