### ISSUE TITLE
where is 50,000

### ISSUE THREAD

**Issue by OMEGA640** [Gsnipe1blookethacks/blookethack#6]
ME NEED TOKENS

**Comment by Snowflake-Coder-H2o** [comment]
to bad?

**Comment by Gsnipe1blookethacks** [comment]
Sorry this code doesn’t work anymore after the recent valence changes

**Comment by Gsnipe1blookethacks** [comment]
Since this issue has been resolved I will now delete it


thanks,Gsnipe1
