### ISSUE TITLE
coin site blocked

### ISSUE THREAD

**Issue by OMEGA640** [Gsnipe1blookethacks/blookethack#7]
it's blocked ttps://sites.google.com/stu.rossvalleyschools.org/blooketcoinhack/home

**Comment by Gsnipe1blookethacks** [comment]
I am sorry to hear this I will edit them to try and unblock them, for now the normal hacks work

**Comment by Park-Sauce** [comment]
It doesn't seem to be blocked (PO)

**Comment by Gsnipe1blookethacks** [comment]
I have edited it. If it is still blocked than you will have to use the zip downloader or just use the codes on the git hub page

**Comment by Gsnipe1blookethacks** [comment]
This issue has been resolved. I will now delete it

thanks,Gsnipe1
